force-app/main/default/objects/Case/fields/PMT_Days_Open__c.field-meta.xml
<CustomField>
    <fullName>PMT_Days_Open__c</fullName>
    <formula>if(ISBLANK(ClosedDate),
Now()- CreatedDate, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PMT Days Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/PMT_Project__c.field-meta.xml
<CustomField>
    <fullName>PMT_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PMT Project</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>Cases (Related Project)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/PMT_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Used to capture errors occurred operations.</description>
    <label>PMT Error Log</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>PMT Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Error_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Apex class whose execution failed</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Actual error caused function execution</description>
    <label>Error Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Apex method which get failed</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Project__c/PMT_Project__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A project can one or more phases</description>
    <label>PMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Setting__mdt/PMT_Setting__mdt.object-meta.xml
<CustomObject>
    <label>PMT Setting</label>
    <pluralLabel>PMT Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMT_Setting__mdt/fields/Allocation_Trigger_Status__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Trigger_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Activates/deactivates the trigger which automates the project sharing. Keep this false, if your sharing model is public read/write for project</description>
    <inlineHelpText>Activates/deactivates the trigger which automates the project sharing. Keep this false, if your sharing model is public read/write for project</inlineHelpText>
    <label>Allocation Trigger Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMT_Setting__mdt/fields/Default_Availability_for_Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Default_Availability_for_Scheduler__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The default availability percentage assigned to the users while creating the availabilities</description>
    <inlineHelpText>The default availability percentage assigned to the users while creating the availabilities</inlineHelpText>
    <label>Default Availability for Scheduler</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMT_Setting__mdt/fields/Resource_Planning_Years_in_Advance__c.field-meta.xml
<CustomField>
    <fullName>Resource_Planning_Years_in_Advance__c</fullName>
    <defaultValue>2</defaultValue>
    <description>The rolling number of years for which the availability is created by the scheduler in advance, so that resource planning can be done in advance for those many number of years</description>
    <inlineHelpText>The rolling number of years for which the availability is created by the scheduler in advance, so that resource planning can be done in advance for those many number of years</inlineHelpText>
    <label>Resource Planning # Years in Advance</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMT_Setting__mdt/fields/Start_Month_of_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Start_Month_of_Fiscal_Year__c</fullName>
    <defaultValue>2</defaultValue>
    <description>This indicates the start of the fiscal year. For example, if value is 2 which means year starts from Feb, 3 for Mar, and so on</description>
    <inlineHelpText>This indicates the start of the fiscal year. For example, if value is 2 which means year starts from Feb, 3 for Mar, and so on</inlineHelpText>
    <label>Start Month of Fiscal Year</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PMT_Utility.cls
/*****************************************************************************************
* Name: PMT_Utility
* Referenced components: 
- PMT_CaseDataTable.cmp
* Test class : PMT_Testcoverage (96%)
******************************************************************************************/
public with sharing class PMT_Utility {
    /*****************************************************************************************
* Method Name: getCasesForProject
* Description: Get list of Cases for a project for the Case Datatable on Project Summary page. Used in PMT_CaseDataTable component
* Parameters : Project recordId
* Return Values: list of cases
* *****************************************************************************************/  
    @AuraEnabled
    public static List<Case> getCasesForProject(Id recordId){    
        List<case> cases = new List<case>();
        //Calling util method to check CRUD
        List<String> lstOfCaseFields = new List<String>{'CaseNumber', 'Subject', 'PMT_Days_Open__c', 'Description', 'Type', 'Status', 'Priority', 'PMT_Project__c'};        
        boolean hasAccess = validateCRUD('Case', lstOfCaseFields, 'isAccessible');
        
        if(hasAccess){  
            cases = [SELECT id,CaseNumber,Subject,PMT_Days_Open__c,Description,Type,Status,Priority,PMT_Project__c FROM Case 
                     WHERE PMT_Project__c =:recordId AND RecordType.DeveloperName =: System.Label.PMT_Project_Record_Type_on_Case ORDER BY Priority ASC, Type ASC limit: limits.getLimitQueryRows()];                                     
            return cases;
            
        }else{
            throw new AuraHandledException('You don\'t have access to related Cases. Please contact system administrator.');
        } 
    }
    
    /*****************************************************************************************
    * Method Name: validateCRUD
    * Description: Generic method to check CRUD access on object and fields
    * Parameters : sObject API name, list of fields, type of access to check
    * Return Values: boolean
    * *****************************************************************************************/  
    public static boolean validateCRUD(String sObjectName, List<String> lstOfFieldAPIs, String accessCheck){    
        
        Schema.DescribeSobjectResult[] result = Schema.describeSObjects(new String[]{sObjectName});
        
        Map<String, Schema.SObjectField> fieldMap = result[0].fields.getMap();
        
        if(lstOfFieldAPIs == null ){ // Check object level access
            if( (accessCheck.equalsIgnoreCase('isDeletable') && result[0].isDeletable()) ||
               (accessCheck.equalsIgnoreCase('isUpdateable') && result[0].isUpdateable()) ||
               (accessCheck.equalsIgnoreCase('isCreateable') && result[0].isCreateable()) ||
               (accessCheck.equalsIgnoreCase('isAccessible') && result[0].isAccessible())) {
                   return true;
               }else{
                   return false;
               }
        } else if(lstOfFieldAPIs != null){// Check field level access 
            for (String field : lstOfFieldAPIs) {
                if (accessCheck.equalsIgnoreCase('isAccessible') && !fieldMap.get(field).getDescribe().isAccessible()) {
                    return false;
                }else if (accessCheck.equalsIgnoreCase('isUpdateable') && !fieldMap.get(field).getDescribe().isUpdateable()) {
                    return false;
                }else if (accessCheck.equalsIgnoreCase('isCreateable') && !fieldMap.get(field).getDescribe().isCreateable()) {
                    return false;
                }
            }
            return true;
        }else{
            return false;
        }        
    }
    
    /*****************************************************************************************
    * Method Name: getPMTSettings
    * Description: Get settings stored in mdt
    * Parameters : settingName
    * Return Values: PMT_Setting__mdt
    * *****************************************************************************************/    
    public static PMT_Setting__mdt getPMTSettings(String settingName){
        PMT_Setting__mdt settings;
        try{
            settings = [select id, MasterLabel, DeveloperName, Allocation_Trigger_Status__c, Default_Availability_for_Scheduler__c, Resource_Planning_Years_in_Advance__c, Start_Month_of_Fiscal_Year__c from PMT_Setting__mdt where DeveloperName=:settingName with security_enforced limit 1];
        }
        catch(Exception e){
            //If settings not found, create record to return
            settings = new PMT_Setting__mdt();
            settings.MasterLabel='Default';
            settings.DeveloperName='Default';
            settings.Allocation_Trigger_Status__c = false;
            settings.Default_Availability_for_Scheduler__c = 100;
            settings.Resource_Planning_Years_in_Advance__c = 2;
            settings.Start_Month_of_Fiscal_Year__c = 2;
            
            List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
                if(PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
                    INSERT new PMT_Error_Log__c(Apex_Class__c='PMT_Utility', Error_Message__c = e.getMessage() , Method_Name__c = 'getPMTSettings');
                }
        }
        return settings;
    }
}