force-app/main/default/objects/PMT_Error_Log__c/PMT_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Used to capture errors occurred operations.</description>
    <label>PMT Error Log</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>PMT Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Error_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Apex class whose execution failed</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Actual error caused function execution</description>
    <label>Error Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Apex method which get failed</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/PMT_Resource_Availability__c.object-meta.xml
<CustomObject>
    <description>Stores availability of a resource</description>
    <label>PMT Resource Availability</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Resource Availibility No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <description>Availability for April month</description>
    <label>Apr</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <description>Availability for August month</description>
    <label>Aug</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <description>Availability for December month</description>
    <label>Dec</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <description>Availability for February month</description>
    <label>Feb</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>The year for which availability is provided</description>
    <label>Fiscal Year</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <description>Availability for January month</description>
    <label>Jan</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <description>Availability for July month</description>
    <label>Jul</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <description>Availability for June month</description>
    <label>Jun</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <description>Availability for March month</description>
    <label>Mar</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <description>Availability for May month</description>
    <label>May</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <description>Availability for November month</description>
    <label>Nov</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <description>Availability for October month</description>
    <label>Oct</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <description>Availability for September month</description>
    <label>Sep</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for which availability is defined</description>
    <label>User</label>
    <referenceTo></referenceTo>
    <relationshipName>Resource_Availability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PMT_CreateResourceAvailability.cls
/*******************************************************************************************
* Name: PMT_CreateResourceAvailability
* Description: It creates Resource availability for users for future years in advance when scheduler runs.
* Test class: PMT_scheduerResourceAvailabilityTest (86%)
*******************************************************************************************/
public with sharing class PMT_CreateResourceAvailability{
    /*****************************************************************
    * Method Name : insertResourceAvailability
    * Params : String of JSON consist of Map of UserId's and respective fiscal year list 
    * Return : NA
    * Description : Creates resource availability for all mentioned users for next n fiscal years.
    * **************************************************************/
    @future
    public static void insertResourceAvailability(String jsonOfResourceAndFiscalyearList){
        Map<Id,Set<String>> mapOfResourceAndFiscalyearList = (Map<Id,Set<String>>) JSON.deserialize(String.escapeSingleQuotes(jsonOfResourceAndFiscalyearList), Map<Id,Set<String>>.class);
        Set<String> setOfFutureYRAvailabilityRequired;
        List<PMT_Resource_Availability__c> lstOfNewResourceAvailability = new List<PMT_Resource_Availability__c>();
        List<PMT_Error_Log__c> lstOfErrorLogs = new List<PMT_Error_Log__c>();
        List<String> lstOfDummyAvailabilityPresent = new List<String>();
        
        Integer resourceAvailability = 100; //  Default resource availability will be set to 100
        //
        try{ 
            //Find out resource availability should be present
            resourceAvailability = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Default_Availability_for_Scheduler__c);
            setOfFutureYRAvailabilityRequired = getFutureAvailabilityYears(mapOfResourceAndFiscalyearList);
            //Check for each user availability is present as per required for future years
            for(Id userId : mapOfResourceAndFiscalyearList.keySet()){
                for(String fiscalYearRequired : setOfFutureYRAvailabilityRequired){
                    if(!mapOfResourceAndFiscalyearList.get(userId).contains(fiscalYearRequired)){
                        PMT_Resource_Availability__c resARec = new PMT_Resource_Availability__c(Fiscal_Year__c = fiscalYearRequired, User__c = userId,
                                                                                                Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                                                Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                                                May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                                                Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                                                Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                                                Nov__c = resourceAvailability, Dec__c = resourceAvailability);
                        lstOfNewResourceAvailability.add(resARec);
                    }
                }
            }
            
            //For each FY create availability without user
            for(PMT_Resource_Availability__c availabilityRec : [SELECT Id,User__c,Fiscal_Year__c FROM PMT_Resource_Availability__c WHERE Fiscal_Year__c IN: setOfFutureYRAvailabilityRequired AND User__c = '' limit :Limits.getLimitQueryRows()]){
                lstOfDummyAvailabilityPresent.add(availabilityRec.Fiscal_Year__c);
            }
            
            for(String fiscalYearRequired : setOfFutureYRAvailabilityRequired){
                if(!lstOfDummyAvailabilityPresent.contains(fiscalYearRequired)){
                    PMT_Resource_Availability__c resARec = new PMT_Resource_Availability__c(Fiscal_Year__c = fiscalYearRequired,
                                                                                            Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                                            Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                                            May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                                            Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                                            Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                                            Nov__c = resourceAvailability, Dec__c = resourceAvailability);
                    
                    lstOfNewResourceAvailability.add(resARec);
                }
            }
            
            List<String> lstOfAvailabilityFields = new List<String>{'Fiscal_Year__c', 'Jan__c','Feb__c','Mar__c','Apr__c','May__c','Jun__c','Jul__c','Aug__c','Sep__c','Oct__c','Nov__c','Dec__c'};
            
            if(!lstOfNewResourceAvailability.isEmpty() && PMT_Utility.validateCRUD('PMT_Resource_Availability__c', lstOfAvailabilityFields, 'isCreatable')){				
                Database.SaveResult[] srList = Database.INSERT(lstOfNewResourceAvailability,false);
                for (Database.SaveResult sr : srList) {
                    if (!sr.isSuccess()){ 
                        // Operation failed, so get all errors                
                        for(Database.Error err : sr.getErrors()) {
                            lstOfErrorLogs.add(new PMT_Error_Log__c(Apex_Class__c='PMT_CreateResourceAvailability', Error_Message__c = err.getMessage() + 'and fields that affected this error:' + err.getFields(), Method_Name__c = 'insertResourceAvailability'));
                            
                        }
                    }
                }                
            }
        }catch(Exception e){
            lstOfErrorLogs.add(new PMT_Error_Log__c(Apex_Class__c='PMT_CreateResourceAvailability', Error_Message__c = e.getMessage() , Method_Name__c = 'insertResourceAvailability'));
        }
        
        List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
            //Calling util method to check CRUD
            if(!lstOfErrorLogs.isEmpty() && PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
                INSERT lstOfErrorLogs;
            }
    }
    
    /*****************************************************************
    * Method Name : getFutureAvailabilityYears
    * Params : map of resource and fiscal year
    * Return : returns the set of years to setup the availability
    * **************************************************************/
    public static Set<String> getFutureAvailabilityYears(Map<Id,Set<String>> mapOfResourceAndFiscalyearList){
        Set<String> setOfFutureYRAvailabilityRequired = new Set<String>();
        Integer fiscalYearStartMonth =  Integer.valueOf(PMT_Utility.getPMTSettings('Default').Start_Month_of_Fiscal_Year__c);
        Integer futureAvailabilityRequired = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Resource_Planning_Years_in_Advance__c);
        Integer futureYearAvailabilityRequired = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Default_Availability_for_Scheduler__c);
        
        //Find out current financial year running and next years for which need to create availability
        Integer currentRunningMonth = Date.Today().Month();
        Integer currentRunningYear = Date.Today().Year();            
        Integer currentfiscalYear;
        //IF start of the year is January, it should show the same year and not with +1
        if(fiscalYearStartMonth==1 || currentRunningMonth < fiscalYearStartMonth){
            currentfiscalYear = currentRunningYear;
        }else{
            currentfiscalYear = currentRunningYear + 1;
        }
        
        for(Integer i=currentfiscalYear; i<=currentfiscalYear+futureAvailabilityRequired; i++){
            setOfFutureYRAvailabilityRequired.add('FY'+String.valueOf(i).substring(2, 4));
        }
        
        //Find out User wise availability still present **Verify filters
        for(PMT_Resource_Availability__c availabilityRec : [SELECT Id,User__c,Fiscal_Year__c FROM PMT_Resource_Availability__c WHERE Fiscal_Year__c IN: setOfFutureYRAvailabilityRequired AND User__c IN: mapOfResourceAndFiscalyearList.keySet() limit :Limits.getLimitQueryRows()]){ 
            if(mapOfResourceAndFiscalyearList.containsKey(availabilityRec.User__c)){
                Set<String> setOfFiscalYear = mapOfResourceAndFiscalyearList.get(availabilityRec.User__c);
                setOfFiscalYear.add((availabilityRec.Fiscal_Year__c).touppercase());
                mapOfResourceAndFiscalyearList.put(availabilityRec.User__c, setOfFiscalYear);
            }
        }
        return setOfFutureYRAvailabilityRequired;
    }
    
    /*****************************************************************
    * Method Name : createRAOnUserInsert
    * Params : List of UserId's 
    * Return : NA
    * Description : Using insertResourceAvailability method creates resource availability for mentioned users
    * **************************************************************/
    @InvocableMethod(label='Create PMT Resource Availability on User creation')
    public static void createRAOnUserInsert(List<Id> lstOfUserIds){
        Map<Id,Set<String>> mapOfResourceAndFiscalyearList = new Map<Id,Set<String>>();
        
        for(Id userId : lstOfUserIds){
            mapOfResourceAndFiscalyearList.put(userId, new Set<String>());
        }
        
        insertResourceAvailability(JSON.serialize(mapOfResourceAndFiscalyearList));
    }
}