force-app/main/default/objects/PMT_Error_Log__c/PMT_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Used to capture errors occurred operations.</description>
    <label>PMT Error Log</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>PMT Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Error_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>Apex class whose execution failed</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Actual error caused function execution</description>
    <label>Error Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Apex method which get failed</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/PMT_Resource_Allocation__c.object-meta.xml
<CustomObject>
    <description>Stores the allocation of the resource for a requirement</description>
    <label>PMT Resource Allocation</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Allocated_Resource_Id__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Resource_Id__c</fullName>
    <formula>Resource_Availability__r.Flair_Employee__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allocated Resource Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipName>Resource_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Resource_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Resource_IsActive__c</fullName>
    <formula>Resource_Availability__r.Flair_Employee__r.flair__Active__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Resource_Name__c</fullName>
    <formula>Resource_Availability__r.Flair_Employee__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resource Name</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Task__c/fields/Assigned_To1__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Employee</referenceTo>
    <relationshipName>PMT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>The general description of the task. For example, what is the purpose of the task.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Is_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/On_Hold_Reason__c.field-meta.xml
<CustomField>
    <fullName>On_Hold_Reason__c</fullName>
    <inlineHelpText>If blocked, why?</inlineHelpText>
    <label>On Hold Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Percentage_Completion__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Completion__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Task Completion %</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <formula>CASESAFEID(Phase__r.Project__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Id</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Sign_off_status__c.field-meta.xml
<CustomField>
    <fullName>Sign_off_status__c</fullName>
    <label>Sign-off status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed, not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Status_Icon__c.field-meta.xml
<CustomField>
    <fullName>Status_Icon__c</fullName>
    <formula>IF(AND(Days_Late__c &gt;0,TEXT(Status__c) &lt;&gt; &quot;On Hold&quot;),IMAGE(&quot;/resource/PMT_Status_Images/PMT_warning_60.png&quot;,&quot;Late&quot;,20,20), 
IF( TEXT(Sign_off_status__c) = &quot;Approved&quot;, IMAGE(&quot;/resource/PMT_Status_Images/PMT_approval.png&quot;,&quot;Approved&quot;,20,20), 
CASE( TEXT(Status__c) , 
&quot;Not Started&quot;, IMAGE(&quot;/resource/PMT_Status_Images/PMT_routing_offline_60.png&quot;,&quot;Incomplete&quot;,20,20), 
&quot;In Progress&quot;, IMAGE(&quot;/resource/PMT_Status_Images/PMT_Clock.png&quot;,&quot;In Progress&quot;,20,20), 
&quot;On Hold&quot;,IMAGE(&quot;/resource/PMT_Status_Images/PMT_error_60.png&quot;,&quot;On Hold&quot;,20,20), 
IMAGE(&quot;/resource/PMT_Status_Images/PMT_success_60.png&quot;,&quot;Closed&quot;,20,20))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Status_Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Status_Icon_Name__c</fullName>
    <formula>IF(AND(Days_Late__c &gt;0,TEXT(Status__c) &lt;&gt; &quot;On Hold&quot;),&quot;utility:warning&quot;, 
IF( TEXT(Sign_off_status__c) = &quot;Approved&quot;, &quot;utility:approval&quot;, 
CASE( TEXT(Status__c) , 
&quot;Not Started&quot;, &quot;utility:routing_offline&quot;, 
&quot;In Progress&quot;, &quot;utility:clock&quot;, 
&quot;On Hold&quot;,&quot;utility:error&quot;, 
&quot;utility:success&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Icon Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PMT_TaskandPhaseManagementCtrl.cls
/*************************************************
* Name: PMT_TaskandPhaseManagementCtrl
* Description: Helper for Task Management related components:
            - PMT_TaskTableEditor.cmp
            - PMT_CreateMultiPhases
            - PMT_CreateMultiTasks.cmp
* Test class: PMT_TaskandPhaseManagementCtrlTest (84%)
* ***********************************************/

public with Sharing class PMT_TaskandPhaseManagementCtrl{
    
    /*************************************************
* Name: CreateTasksWrapper
* Used by : PMT_CreateMultiTasks.cmp
* ***********************************************/
    
    public class CreateTasksWrapper
    {
        @AuraEnabled public List<Map<String, String>> phasesList;
        @AuraEnabled public List<Map<String, String>> memberList;      
    }
    
    /************************************************
* Method Name: getTaskWrapper 
* Description: Get tasks for the current project
* Component(s): PMT_CreateMultiTasks.cmp
* Parameters : project id
* Return Values:  CreateTasksWrapper instance
* ***********************************************/    
    @AuraEnabled
    public static CreateTasksWrapper getTaskWrapper(Id projectId)
    {
        CreateTasksWrapper taskWrapper = new CreateTasksWrapper();
        //Calling util method to check CRUD
        List<String> lstPhaseFields = new List<String>{'Name', 'Project__c'};
        if(PMT_Utility.validateCRUD('PMT_Phase__c', lstPhaseFields , 'isAccessible')) {
            taskWrapper.phasesList = getPhasesList(projectId);
        }else{
            throw new AuraHandledException('You don\'t have access to PMT phases. Please contact system administartor.');
        }
        
        //Calling util method to check CRUD
        List<String> lstAllocationFields = new List<String>{'Allocated_Resource_Id__c', 'Resource_Name__c'};
        if(PMT_Utility.validateCRUD('PMT_Resource_Allocation__c', lstAllocationFields, 'isAccessible')) {
            taskWrapper.memberList = getMemberList(projectId);
        }else{
            throw new AuraHandledException('You don\'t have access to PMT Resource allocations. Please contact system administartor.');
        }
        
        return taskWrapper;
    }
    
    /*************************************************
* Method Name: getPhasesList
* Description: Get list of Project related Phases
* Component(s): PMT_CreateMultiTasks.cmp
* Parameters : projectId
* Return Values: items
* ***********************************************/  
    private static List<Map<String, String>> getPhasesList(ID projectId) {    
        List<Map<String, String>> items = new List<Map<String, String>>();        
        for (PMT_Phase__c ph : [SELECT id, Name FROM PMT_Phase__c WHERE Project__c =:projectId limit :limits.getLimitQueryRows()]){
            items.add(new Map<String, String>{'value' => ph.Id, 'label'=> ph.Name});
        }
        
        return items;
    }
    
    /*************************************************
* Method Name: getMemberList
* Description: Get list of Project Members
* Component(s): PMT_CreateMultiTasks.cmp
* Parameters : projectId
* Return Values: items
* ***********************************************/    
    private static List<Map<String, String>> getMemberList(ID projectId) {    
        List<Map<String, String>> items = new List<Map<String, String>>();  
        Set<Id> uniqueUserIds = new Set<Id>();
        for (PMT_Resource_Allocation__c mb : [SELECT id, Allocated_Resource_Id__c, Resource_Name__c FROM PMT_Resource_Allocation__c WHERE Project__c =:projectId and Resource_IsActive__c = true limit :limits.getLimitQueryRows()]){
            if(uniqueUserIds.add(mb.Allocated_Resource_Id__c)){
                items.add(new Map<String, String>{'value' => mb.Allocated_Resource_Id__c, 'label'=> mb.Resource_Name__c});
            }
        }
        
        return items;
    }
    
    
    /************************************************
* Method Name: getTasksForProject 
* Description: Get tasks for the current project
* Component(s): PMT_TaskTableEditor.cmp
*Parameters : project id
* Return Values: list of Task
* ***********************************************/    
    @AuraEnabled
    public static List<PMT_Task__c> getTasksForProject(Id projectId)
    {
        List<String> lstTaskFields = new List<String>{'Id','Name','Status__c','Assigned_To1__c','Percentage_Completion__c','Start_Date__c','Due_Date__c','Description__c','On_Hold_Reason__c','Sign_off_status__c','Is_Milestone__c','Phase__c','Status_Icon__c','Status_Icon_Name__c'};
             
        List<String> lstUserFields = new List<String>{'Name'};
        
        List<String> lstPhaseFields = new List<String>{'Name', 'Id'};
		
            //Calling util method to check CRUD
        if(PMT_Utility.validateCRUD('PMT_Task__c', lstTaskFields, 'isAccessible') && PMT_Utility.validateCRUD('User', lstUserFields, 'isAccessible') && PMT_Utility.validateCRUD('PMT_Phase__c', lstPhaseFields, 'isAccessible')){
            
            return [SELECT id,Name,Status__c,Assigned_To1__c,Percentage_Completion__c,Assigned_To1__r.Name,Start_Date__c,Due_Date__c,Description__c,On_Hold_Reason__c,Sign_off_status__c,Is_Milestone__c,Phase__c,Status_Icon__c,Status_Icon_Name__c,Phase__r.Name,
                    Phase__r.Id FROM PMT_Task__c WHERE Project_Id__c=:projectId order by Start_Date__c ASC limit: limits.getLimitQueryRows()];                     
                    
                    
        }else{
            throw new AuraHandledException('Access restricted. Please contact system administartor.');
        }
    }
    
    
    /*************************************************
* Method Name: updateTasks
* Description: Update tasks
* Component(s): PMT_TaskTableEditor.cmp
* Parameters : tasks
* Return Values: list of tasks
* ***********************************************/
    @AuraEnabled
    public static List<PMT_Task__c> updateTasks(List<PMT_Task__c> tasks){
        //Calling util method to check CRUD
        if(PMT_Utility.validateCRUD('PMT_Task__c', null, 'isUpdateable')){ 
            try {            
                if(!tasks.isEmpty()){
                    UPDATE tasks;
                    return tasks;  
                }else{
                    return null;
                }
                
            } catch(Exception e) {
                //Calling util method to check CRUD
                List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
            	if(PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
                	INSERT new PMT_Error_Log__c(Apex_Class__c='PMT_TaskandPhaseManagementCtrl', Error_Message__c = e.getMessage() , Method_Name__c = 'updateTasks');
                }
                AuraHandledException ae = new AuraHandledException('Error occurred while updating task:');
                ae.setMessage(e.getMessage());
                throw ae;
            }
        }else{
            throw new AuraHandledException('You don\'t have access to update PMT tasks. Please contact system administartor.');
        }   
    }  
    
    /*************************************************
* Method Name: deleteRecord
* Description: delete records
* Component(s): PMT_TaskTableEditor.cmp
* Parameters : recordToDelete
* Return Values: null
* ***********************************************/
    @auraEnabled
    public static Boolean deleteRecord(sObject recordToDelete) {
        //Calling util method to check CRUD
        if(PMT_Utility.validateCRUD('PMT_Task__c', null, 'isDeletable')){       
            try {
                DELETE recordToDelete;
                return true;
            } catch(Exception e) {
                List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
            	if(PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
                	INSERT new PMT_Error_Log__c(Apex_Class__c='PMT_TaskandPhaseManagementCtrl', Error_Message__c = e.getMessage() , Method_Name__c = 'deleteRecord');
                }
                return false;
            }
        }else{
            throw new AuraHandledException('You don\'t have access to delete PMT tasks. Please contact system administartor.');
        }   
    }
    
    /*************************************************
* Method Name: submitTaskForApproval
* Description: Submit task for Approval
* Component(s): PMT_TaskTableEditor.cmp
* Parameters : taskId
* Return Values: null
* NOTE: It will need approval process to update Sign off status on task on approval.
* ***********************************************/
    @auraEnabled
    public static Boolean submitTaskForApproval(Id taskId) {        
        Boolean res = false;
        try {
            if(taskId != null) {
                // create the new approval request to submit
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setComments('Submitted for approval.');
                req.setObjectId(taskId);
                // submit the approval request for processing
                Approval.ProcessResult result = Approval.Process(req);
                // display if the reqeust was successful
                if(result.isSuccess()) {
                    res = true;
                } 
                else 
                {
                    return res;
                }
            }
            return res;
        } catch(Exception e) {
            //Calling util method to check CRUD
            List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
            if(PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
            	INSERT new PMT_Error_Log__c(Apex_Class__c='PMT_TaskandPhaseManagementCtrl', Error_Message__c = e.getMessage() , Method_Name__c = 'submitTaskForApproval');
            }
            return false;
        }        
    }
    
    /*************************************************
* Method Name: savePhases
* Description: Create phases on submission
* Component(s): PMT_CreateMultiPhases.cmp
* Parameters : phaseList
* Return Values: null
* ***********************************************/
    @AuraEnabled
    public static void savePhases(List<PMT_Phase__c> phaseList){
        //Calling util method to check CRUD
        if(PMT_Utility.validateCRUD('PMT_Phase__c', null, 'isCreateable')){
            try{
                Insert phaseList;
                
            }catch(Exception e) {   
                //Calling util method to check CRUD
                List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
            	if(PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
                	INSERT new PMT_Error_Log__c(Apex_Class__c='PMT_TaskandPhaseManagementCtrl', Error_Message__c = e.getMessage() , Method_Name__c = 'savePhases');
                }
                AuraHandledException ae = new AuraHandledException('Error occurred while creating phase:');
                ae.setMessage(e.getMessage());
                throw ae;
            }
        }else{
            throw new AuraHandledException('You don\'t have access to create phases. Please contact system administartor.');
        }   
    }
    
    /*************************************************
    * Method Name: getPicklistvalues
    * Description: Get values from picklist fields
    * Component(s): PMT_CreateMultiPhases.cmp
    * Parameters : objectName, field_apiname
    * Return Values: optionlist
    * ***********************************************/
    
    @AuraEnabled
    public static List<String> getPicklistvalues(String objectName, String field_apiname,Boolean nullRequired){
        
        List<String> optionlist = new List<String>();
        
        Map<String,Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> field_map = gd.get(objectName.toLowerCase()).getDescribe().fields.getMap(); 
        List<Schema.PicklistEntry> picklistValues = field_map.get(field_apiname.toLowerCase()).getDescribe().getPickListValues();
        if(nullRequired == true){
            optionlist.add('--None--');
        }
        
        for (Schema.PicklistEntry pv : picklistValues) {
            optionlist.add(pv.getValue());
        }
        return optionlist;
    }
    
    /*************************************************
* Method Name: saveTasks
* Description: Create phases on submission
* Component(s): PMT_CreateMultiTasks.cmp
* Parameters : taskList
* Return Values: taskList
* ***********************************************/    
    @AuraEnabled
    public static void saveTasks(List<PMT_Task__c> taskList){
        //Calling util method to check CRUD
        if(PMT_Utility.validateCRUD('PMT_Task__c', null, 'isCreateable')){
            try{    
                Insert taskList;
            }catch(Exception e) {
                //Calling util method to check CRUD
                List<String> lstOfLogFields = new List<String>{'Apex_Class__c', 'Error_Message__c','Method_Name__c'};
            	if(PMT_Utility.validateCRUD('PMT_Error_Log__c', lstOfLogFields, 'isCreatable')){
	                INSERT new PMT_Error_Log__c(Apex_Class__c='PMT_TaskandPhaseManagementCtrl', Error_Message__c = e.getMessage() , Method_Name__c = 'saveTasks');
                }
                AuraHandledException ae = new AuraHandledException('Error occurred while creating task:');
                ae.setMessage(e.getMessage());
                throw ae;
            }
        }else{
            throw new AuraHandledException('You don\'t have access to create PMT Task. Please contact system administrator.');
        } 
    }
    
    /*************************************************
* Method Name: getTasksList
* Description: Get list of Project tasks from Ids
* Component(s): PMT_TaskTableEditor.cmp
* Parameters : taskIds
* Return Values: tasks list
* ***********************************************/   
    @AuraEnabled
    public static List<PMT_Task__c> getTasksList(List<ID> taskIds) {
        List<PMT_Task__c> items = new List<PMT_Task__c>();
        List<String> lstOfTaskFields = new List<String>{'Id','Assigned_To1__c'};
        //Calling util method to check CRUD
        if(taskIds != null && taskIds.size() > 0 && PMT_Utility.validateCRUD('PMT_Task__c', lstOfTaskFields, 'isAccessible')) {
            items = [select Id, Assigned_To1__c from PMT_Task__c where Id IN: taskIds limit :limits.getLimitQueryRows()];
            return items;
        }else{
            throw new AuraHandledException('You don\'t have access to PMT Task. Please contact system administrator.');
        }
    }
}