sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Program__c/PMT_Program__c.object-meta.xml
<CustomObject>
    <description>Use in Project Management Tool to record Programs and related projects.</description>
    <label>PMT Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Program__c/fields/Program_Health__c.field-meta.xml
<CustomField>
    <fullName>Program_Health__c</fullName>
    <label>Program Health</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMT_Status</valueSetName>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/PMT_Project__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A project can one or more phases</description>
    <label>PMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Level_of_Effort__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Effort__c</fullName>
    <label>Level of Effort</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Path_to_Green__c.field-meta.xml
<CustomField>
    <fullName>Path_to_Green__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Path to Green</label>
    <type>TextArea</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>PMT_Program__c</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Project_Category__c.field-meta.xml
<CustomField>
    <fullName>Project_Category__c</fullName>
    <label>Project Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Non IT</fullName>
            </value>
            <value>
                <fullName>SteerCo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Project_Health__c.field-meta.xml
<CustomField>
    <fullName>Project_Health__c</fullName>
    <description>Project Status to be used in reporting</description>
    <inlineHelpText>On Track = Will meet deadline / At Risk = At risk for missing deadline / Late = Will miss deadline</inlineHelpText>
    <label>Project Health</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMT_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Current Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Initiate</fullName>
                <default>true</default>
                <label>Initiate</label>
            </value>
            <value>
                <fullName>Execute</fullName>
            </value>
            <value>
                <fullName>Transition</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/fields/SystemsImpacted__c.field-meta.xml
<CustomField>
    <fullName>SystemsImpacted__c</fullName>
    <inlineHelpText>Please hold &apos;Ctrl&apos; for selecting multiple options</inlineHelpText>
    <label>System(s) Impacted</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Assigned_To1__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/PMT_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>On Track</fullName>
        <default>true</default>
        <label>On Track</label>
    </customValue>
    <customValue>
        <fullName>At Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Late</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed, not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <isActive>false</isActive>
        <label>Complete</label>
    </customValue>
    <description>PMT Status list for Project</description>
    <masterLabel>PMT_Status</masterLabel>
</GlobalValueSet>

sfdc-pmt/main/default/classes/PMT_GanttCtrlTest.cls
/******************************************************************************************************
 * Name: PMT_GanttCtrlTest.apxc
 * Test class for : PMT_GanttCtrl (87%)
 * Version : 56 
 ******************************************************************************************************/

@isTest
public with sharing class PMT_GanttCtrlTest {
    /* Create Test Data */
    @testSetup static void setup() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

        User testUser = new User(Alias = 'standt', Email = 'standarduser@pmtgantt.com',
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US', ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles', UserName = 'standarduser@pmtgantt.com');

        insert testUser;

        List<PermissionSetAssignment> lstOfPSA = new List<PermissionSetAssignment>();

        for (PermissionSet psRec: [SELECT Id FROM PermissionSet WHERE Name IN('PMT_User')]) {
            PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = psRec.Id);
            lstOfPSA.add(psa);
        }

        INSERT lstOfPSA;

        System.runAs(testUser) {
            List<PMT_Task__c> lstOfTask = new List<PMT_Task__c>();

            //Project 1 setup
            PMT_Program__c pg1 = new PMT_Program__c();
            pg1.Name = 'Test Program 1';
            pg1.Program_Health__c = 'On Track';
            INSERT pg1;

            PMT_Project__c prj1 = new PMT_Project__c();
            prj1.Name = 'New project 1';
            prj1.Program__c = pg1.Id;
            prj1.Project_Status__c = 'Execute';
            prj1.Project_Category__c = 'IT';
            prj1.Level_of_Effort__c = 'Medium';
            prj1.Project_Health__c = 'On Track';
            INSERT prj1;

            PMT_Phase__c ph1 = new PMT_Phase__c();
            ph1.Name = 'test phase 1';
            ph1.Project__c = prj1.Id;
            INSERT ph1;

            PMT_Phase__c ph2 = new PMT_Phase__c();
            ph2.Name = 'test phase 2';
            ph2.Project__c = prj1.Id;
            INSERT ph2;

            PMT_Task__c tsk1 = new PMT_Task__c();
            tsk1.Name = 'Task 01 for project 1';
            tsk1.Phase__c = ph1.Id;
            tsk1.Assigned_To1__c = UserInfo.getUserId();
            lstOfTask.add(tsk1);

            //Project 2 setup
            PMT_Program__c pg2 = new PMT_Program__c();
            pg2.Name = 'Test Program 2';
            pg2.Program_Health__c = 'On Track';
            INSERT pg2;

            PMT_Project__c prj2 = new PMT_Project__c();
            prj2.Name = 'New project 2';
            prj2.Program__c = pg2.Id;
            prj2.Path_to_Green__c = 'Test';
            prj2.Level_of_Effort__c = 'Medium';
            prj2.Project_Status__c = 'Transition';
            prj2.Project_Category__c = 'Non IT';
            prj2.Project_Health__c = 'At Risk';
            INSERT prj2;

            PMT_Phase__c ph3 = new PMT_Phase__c();
            ph3.Name = 'test phase 2';
            ph3.Project__c = prj2.Id;
            INSERT ph3;

            PMT_Task__c tsk2 = new PMT_Task__c();
            tsk2.Name = 'Task 02 for project 2';
            tsk2.Phase__c = ph3.Id;
            tsk2.Assigned_To1__c = UserInfo.getUserId();
            tsk2.Start_Date__c = System.Today();
            tsk2.Due_Date__c = System.Today() + 300;
            lstOfTask.add(tsk2);

            INSERT lstOfTask;
        }
    }

    static testmethod void testDefaultFilters() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'standarduser@pmtgantt.com'];
        System.runAs(testUser) {
            Test.startTest();
            List<PMT_GanttCtrl.GanttDataWrapper> result1 = PMT_GanttCtrl.fetchGanttData(92, System.Today(), '', 'All', 'All', 'All','' ,'All', 'All' , 'Start_Date__c Asc');
            List<PMT_GanttCtrl.GanttDataWrapper> result2 = PMT_GanttCtrl.fetchGanttData(31, System.Today(), '', 'All', 'All', 'All','project' ,'All', 'All' , 'Start_Date__c Desc');
			List<PMT_GanttCtrl.GanttDataWrapper> result3 = PMT_GanttCtrl.fetchGanttData(31, System.Today(), '', 'All', 'All', 'All','project' ,'All', 'All' , 'Due_Date__c Asc');
            
            system.assertEquals(true, result1.size() > 0);
            system.assertEquals(true, result2.size() > 0);
            system.assertEquals(true, result3.size() > 0);
            Test.stopTest();
        }
    }

    static testmethod void testOtherFilters() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'standarduser@pmtgantt.com'];
        System.runAs(testUser) {

            Test.startTest();
            List<PMT_GanttCtrl.GanttDataWrapper> result = PMT_GanttCtrl.fetchGanttData(10, System.Today(), '', 'Execute', 'On Track', 'Inov8','' ,'Non IT', 'All','Due_Date__c Asc');

            system.assertEquals(true, result.size() == 0);
            Test.stopTest();
        }
    }

    static testmethod void testProgramFilter() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'standarduser@pmtgantt.com'];
        System.runAs(testUser) {
            PMT_Program__c prg = [SELECT Id FROM PMT_Program__c WHERE Name = 'Test Program 1'];

            Test.startTest();
            List<PMT_GanttCtrl.GanttDataWrapper> result = PMT_GanttCtrl.fetchGanttData(10, System.Today(), '', 'Execute', 'All', 'All', '', 'All', String.valueOf(prg.Id),'Due_Date__c Desc');
            system.assertEquals(true, result.size() > 0);
            Test.stopTest();
        }
    }

    static testmethod void testUpdateTask() {
        User testUser = [SELECT Id FROM User WHERE UserName = 'standarduser@pmtgantt.com'];
        System.runAs(testUser) {
            PMT_Task__c task = [SELECT Id FROM PMT_Task__c WHERE Name = 'Task 01 for project 1'];
            Test.startTest();

            String result = PMT_GanttCtrl.saveTask(task.Id, System.Today(), System.Today()+30);
            Date start_Date = System.Today();
            Date end_Date = start_Date + 4 - 1;

            task = [SELECT Id, Start_Date__c, Due_Date__c FROM PMT_Task__c WHERE Name = 'Task 01 for project 1'];
            system.assertEquals(true, result == 'Task updated successfully.', 'Error updating Task');
            Test.stopTest();
        }
    }

    static testmethod void testUpdateTaskNegative() {
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];

        User testUser = new User(Alias = 'standt', Email = 'standarduser@pmtgantt.com',
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US', ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles', UserName = 'standarduser@pmtgantttest.com');

        insert testUser;
        System.runAs(testUser) {
            try {
                PMT_Task__c task = [SELECT Id FROM PMT_Task__c WHERE Name = 'Task 01 for project 1'];
                Test.startTest();
                String result = PMT_GanttCtrl.saveTask(task.Id, System.Today()+10, System.Today());
                Test.stopTest();
            } catch (Exception ex) {}
        }
    }

    static testmethod void testFilterValues() {
        Map<String, String> mapOfHealthValues = PMT_Utility.getPicklistValues('PMT_Project__c', 'Project_Health__c');
        Map<String, String> mapOfCategoryValues = PMT_Utility.getPicklistValues('PMT_Project__c', 'Project_Category__c');
        Map<String, String> mapOfSystemValues = PMT_Utility.getPicklistValues('PMT_Project__c', 'SystemsImpacted__c');
        Map<String, String> mapOfProgressValues = PMT_Utility.getPicklistValues('PMT_Project__c', 'Project_Status__c');

        User testUser = [SELECT Id FROM User WHERE UserName = 'standarduser@pmtgantt.com'];

        System.runAs(testUser) {
            Test.startTest();
            PMT_GanttCtrl.GanttFliterWrapper result = PMT_GanttCtrl.getGanttFilters();

            system.assertEquals(true, result.prjhealth.size() == mapOfHealthValues.size(), 'All values of Project health must be fetched.');
            system.assertEquals(true, result.prjcategory.size() == mapOfCategoryValues.size(), 'All values of Project category must be fetched.');
            system.assertEquals(true, result.sysimpacted.size() == mapOfSystemValues.size(), 'All values of System impacted must be fetched.');
            system.assertEquals(true, result.prjprogress.size() == mapOfProgressValues.size(), 'All values of Project status must be fetched.');
            Test.stopTest();
        }
    }
}