sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/PMT_Project__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A project can one or more phases</description>
    <label>PMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Initial_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Initial End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Level_of_Effort__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Effort__c</fullName>
    <label>Level of Effort</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F&amp;S</fullName>
            </value>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>Q2O</fullName>
            </value>
            <value>
                <fullName>R2R</fullName>
            </value>
            <value>
                <fullName>New Entity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/PMT_Resource_Allocation__c.object-meta.xml
<CustomObject>
    <description>Stores the allocation of the resource for a requirement</description>
    <label>PMT Resource Allocation</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <label>Apr</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <label>Aug</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <label>Dec</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <label>Feb</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <formula>Resource_Availability__r.Fiscal_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Year</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <label>Jan</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <label>Jul</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <label>Jun</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <label>Mar</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <label>May</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <label>Nov</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <label>Oct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipName>Resource_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Resource_Availability__c.field-meta.xml
<CustomField>
    <fullName>Resource_Availability__c</fullName>
    <label>Resource Availability</label>
    <referenceTo>PMT_Resource_Availability__c</referenceTo>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMT_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <label>Sep</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/PMT_Resource_Availability__c.object-meta.xml
<CustomObject>
    <description>Stores availability of a resource</description>
    <label>PMT Resource Availability</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Resource Availibility No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <description>Availability for April month</description>
    <label>Apr</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <description>Availability for August month</description>
    <label>Aug</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <description>Availability for December month</description>
    <label>Dec</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <description>Availability for February month</description>
    <label>Feb</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>The year for which availability is provided</description>
    <label>Fiscal Year</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <description>Availability for January month</description>
    <label>Jan</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <description>Availability for July month</description>
    <label>Jul</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <description>Availability for June month</description>
    <label>Jun</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <description>Availability for March month</description>
    <label>Mar</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <description>Availability for May month</description>
    <label>May</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <description>Availability for November month</description>
    <label>Nov</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <description>Availability for October month</description>
    <label>Oct</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <description>Availability for September month</description>
    <label>Sep</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Calculates the start date using FYXX format</description>
    <formula>If($CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c==1,
DATE(
VALUE(MID(TEXT(YEAR(TODAY())),1,2)
+
MID(Fiscal_Year__c, 3, 2)),
$CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c,1)
,
DATE(
VALUE(MID(TEXT(YEAR(TODAY())),1,2)
+
MID(Fiscal_Year__c, 3, 2))-1,
$CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c,1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for which availability is defined</description>
    <label>User</label>
    <referenceTo></referenceTo>
    <relationshipName>Resource_Availability</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/classes/PMT_TaskandPhaseManagementCtrlTest.cls
/*************************************************
* Name: PMT_TaskandPhaseManagementCtrlTest
* Test class for : PMT_TaskandPhaseManagementCtrl (84%)
* ***********************************************/
@isTest
public class PMT_TaskandPhaseManagementCtrlTest {
	@testSetup static void setup(){
		List<PMT_Task__c> lstOfTasks = new List<PMT_Task__c>();
        Integer resourceAvailability = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Default_Availability_for_Scheduler__c);
        
        //PMT project record
		PMT_Project__c project = new PMT_Project__c(Name='Project Controller Test', 
													Portfolio__c='R2R',
													Initial_End_Date__c=System.today()+30,
													Initial_Start_Date__c=System.today(),
                                                   Level_of_Effort__c = 'Small');
        INSERT project;
		
		//PMT phase record
		PMT_Phase__c phases = new PMT_Phase__c(Name = 'Phase 1',
												Project__c = project.Id);
        INSERT phases;
		
		//PMT resource availability record
        PMT_Resource_Availability__c resAvail = new PMT_Resource_Availability__c( User__c = UserInfo.getUserId(),
                                                                                     Fiscal_Year__c = 'FY21',
                                                                                     Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                                     Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                                     May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                                     Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                                     Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                                     Nov__c = resourceAvailability, Dec__c = resourceAvailability);
																					 
		INSERT resAvail;
        
        //Allocation records
        PMT_Resource_Allocation__c resAllocation = new PMT_Resource_Allocation__c(Project__c = project.Id,
                                                                                  Resource_Availability__c = resAvail.Id,
                                                                                  Role__c = 'SME' );                                                                                        
        INSERT resAllocation;
        
        //PMT Task records
		PMT_Task__c task1 = new PMT_Task__c(Name = 'Task 1', 
											Status__c = 'Not Started',
											Start_Date__c = System.today(), 
											Due_Date__c = System.today()+30, 
											Assigned_To1__c = UserInfo.getUserId(),
											Is_Milestone__c = true,
											Phase__c = phases.Id); 
		lstOfTasks.add(task1);
		
        PMT_Task__c task2 = new PMT_Task__c(Name = 'Task 2', 
											Status__c = 'Not Started',
											Start_Date__c = System.today(), 
											Due_Date__c = System.today()+30, 
											Assigned_To1__c = UserInfo.getUserId(), 
											Is_Milestone__c = false, 
											Phase__c = phases.Id);
        lstOfTasks.add(task2);
		
		INSERT lstOfTasks;
	}
    
    static testmethod void getTasksForProjectTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            Test.startTest();
            List<PMT_Task__c> lstOfResult = PMT_TaskandPhaseManagementCtrl.getTasksForProject(project.Id);
            Test.stopTest();
            system.assertEquals(2, lstOfResult.size(), 'There should be 2 tasks present.');
        }
    }
	
	static testmethod void updateTaskTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Task__c taskrec = [SELECT Id, Status__c FROM PMT_Task__c LIMIT 1];
            taskrec.Status__c = 'In Progress';
            
            Test.startTest();
            List<PMT_Task__c> lstOfResult = PMT_TaskandPhaseManagementCtrl.updateTasks(new List<PMT_Task__c>{taskrec});
            PMT_Task__c taskUpdated = [SELECT Id, Status__c FROM PMT_Task__c LIMIT 1];
            Test.stopTest();
            system.assertEquals('In Progress', taskUpdated.Status__c, 'Task status must be updated.');
        }
    }
    
    static testmethod void updateTaskNegTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Phase__c phase = [SELECT Id FROM PMT_Phase__c LIMIT 1];
            
            //Create Tasks        
            PMT_Task__c task = new PMT_Task__c(Name = 'Task 1', 
                                               Status__c = 'Not Started',
                                               Start_Date__c = System.today(), 
                                               Due_Date__c = System.today()+30, 
                                               Assigned_To1__c = UserInfo.getUserId(),
                                               Is_Milestone__c = true,
                                               Phase__c = phase.Id); 
            
            Test.startTest();
            try{
                List<PMT_Task__c> lstOfResult = PMT_TaskandPhaseManagementCtrl.updateTasks(new List<PMT_Task__c>{task});
            }catch(Exception e){
                System.assertEquals(true, e.getMessage().contains('error'),'The error should occur');
            }
            
            Test.stopTest();
        }
    }
    
    static testmethod void deleteRecordTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_Global_Admin'});
        System.runAs(testUser){
            PMT_Task__c taskrec = [SELECT Id, Status__c FROM PMT_Task__c LIMIT 1];
            
            Test.startTest();
            Boolean result = PMT_TaskandPhaseManagementCtrl.deleteRecord(taskrec);
            List<PMT_Task__c> lstOfResult = [SELECT Id, Status__c FROM PMT_Task__c];
            Test.stopTest();
            system.assertEquals(1, lstOfResult.size(), 'Only 1 task should be present on delete.');
        }
    }
    
    static testmethod void deleteRecordNegTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_Global_Admin'});
        System.runAs(testUser){
            PMT_Phase__c phase = [SELECT Id FROM PMT_Phase__c LIMIT 1];
            
            //Create Tasks        
            PMT_Task__c task = new PMT_Task__c(Name = 'Task 1', 
                                               Status__c = 'Not Started',
                                               Start_Date__c = System.today(), 
                                               Due_Date__c = System.today()+30, 
                                               Assigned_To1__c = UserInfo.getUserId(),
                                               Is_Milestone__c = true,
                                               Phase__c = phase.Id); 
            
            Test.startTest();
            Boolean result = PMT_TaskandPhaseManagementCtrl.deleteRecord(task);
            system.assertEquals(false, result, 'There should be error.');
            Test.stopTest();    
        }
    }
	
    static testmethod void savePhasesTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            
            //Create Phases        
            PMT_Phase__c phase = new PMT_Phase__c(Name='Phase 3', Project__c = project.Id);
            Test.startTest();
            PMT_TaskandPhaseManagementCtrl.savePhases(new List<PMT_Phase__c> {phase});
            
            PMT_Project__c projectUpdated = [SELECT Id, (SELECT Id FROM Project_Phases__r) FROM PMT_Project__c WHERE Id=: project.Id];			
            system.assertEquals(2, projectUpdated.Project_Phases__r.size(), 'There should be 2 phases available.');
            Test.stopTest();
        }
        
	}
    
    static testmethod void savePhasesNegTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            //Create Phases        
            PMT_Phase__c phase = new PMT_Phase__c(Name='Phase 3');
            Test.startTest();
            try{
                PMT_TaskandPhaseManagementCtrl.savePhases(new List<PMT_Phase__c> {phase});
            }catch(Exception e){
                System.assertEquals(true, e.getMessage().contains('error'),'The error should occur for negative test');
            }
            Test.stopTest();
        }
	}
    
    static testmethod void saveTasksTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Phase__c phase = [SELECT Id FROM PMT_Phase__c LIMIT 1];
            
            //Create Tasks        
            PMT_Task__c task = new PMT_Task__c(Name = 'Task 1', 
                                               Status__c = 'Not Started',
                                               Start_Date__c = System.today(), 
                                               Due_Date__c = System.today()+30, 
                                               Assigned_To1__c = UserInfo.getUserId(),
                                               Is_Milestone__c = true,
                                               Phase__c = phase.Id); 
            
            Test.startTest();
            PMT_TaskandPhaseManagementCtrl.saveTasks(new List<PMT_Task__c> {task});
            
            PMT_Phase__c phaseUpdated = [SELECT Id, (SELECT Id FROM Project_Tasks__r) FROM PMT_Phase__c WHERE Id =: phase.Id];		
            Test.stopTest();
            system.assertEquals(3, phaseUpdated.Project_Tasks__r.size(), 'There should be 3 task available.');
        }
        
	}
    
    static testmethod void saveTasksNegTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            //Create Tasks        
            PMT_Task__c task = new PMT_Task__c(Name = 'Task 1', 
                                               Status__c = 'Not Started',
                                               Start_Date__c = System.today(), 
                                               Due_Date__c = System.today()+30, 
                                               Assigned_To1__c = UserInfo.getUserId(),
                                               Is_Milestone__c = true); 
            
            Test.startTest();
            try{	
                PMT_TaskandPhaseManagementCtrl.saveTasks(new List<PMT_Task__c> {task});
            }catch(Exception e){
                System.assertEquals(true, e.getMessage().contains('error'),'The error should occur for negative test');
            }					
            Test.stopTest();
        }
	}
    
    static testmethod void getPicklistvaluesTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            Test.startTest();
            List<String> lstOfResult = PMT_TaskandPhaseManagementCtrl.getPicklistvalues('PMT_Task__c','Status__c', false);
            Test.stopTest();
            system.assertEquals(5, lstOfResult.size(), 'There should be 5 task status available.');
        }
	}
    
    static testmethod void getTaskWrapperTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            Test.startTest();
            PMT_TaskandPhaseManagementCtrl.createTasksWrapper options = PMT_TaskandPhaseManagementCtrl.getTaskWrapper(project.Id);
            Test.stopTest();
            system.assertEquals(1, options.phasesList.size(), 'There should be 1 phase available.');
            system.assertEquals(1, options.memberList.size(), 'There should be 1 member available.');
        }
	}
    
    static testmethod void getTasksListTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Task__c taskrec = [SELECT Id FROM PMT_Task__c LIMIT 1]; 
            
            Test.startTest();
            List<PMT_Task__c> lstOfResult = PMT_TaskandPhaseManagementCtrl.getTasksList(new List<ID>{taskrec.Id});
            Test.stopTest();
            system.assertEquals(true, lstOfResult[0].Assigned_To1__c != null, 'Assigned to field must be queried.');
        }
	}
    
    static testmethod void submitTaskForApprovalTestCase(){
        User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_User'});
        System.runAs(testUser){
            PMT_Task__c taskrec = [SELECT Id FROM PMT_Task__c LIMIT 1]; 		
            Test.startTest();
            Boolean result = PMT_TaskandPhaseManagementCtrl.submitTaskForApproval(taskrec.Id);
            Test.stopTest();
            system.assertEquals(false, result, 'No approval process found'); //NOTE: Need to update assert on set up of approval process
        }
	}
	
}