sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Program__c/PMT_Program__c.object-meta.xml
<CustomObject>
    <description>Use in Project Management Tool to record Programs and related projects.</description>
    <label>PMT Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Program__c/fields/Program_Health__c.field-meta.xml
<CustomField>
    <fullName>Program_Health__c</fullName>
    <label>Program Health</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMT_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/PMT_Project__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A project can one or more phases</description>
    <label>PMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Project__c/fields/Initial_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_End_Date__c</fullName>
    <label>Initial End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Level_of_Effort__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Effort__c</fullName>
    <label>Level of Effort</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F&amp;S</fullName>
            </value>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>Q2O</fullName>
            </value>
            <value>
                <fullName>R2R</fullName>
            </value>
            <value>
                <fullName>New Entity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Program</label>
    <referenceTo>PMT_Program__c</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/PMT_Resource_Allocation__c.object-meta.xml
<CustomObject>
    <description>Stores the allocation of the resource for a requirement</description>
    <label>PMT Resource Allocation</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <label>Apr</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <label>Aug</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <label>Feb</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <formula>Resource_Availability__r.Fiscal_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Year</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <label>Jan</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <label>Jul</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <label>Jun</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <label>Mar</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <label>May</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipName>Resource_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Resource_Availability__c.field-meta.xml
<CustomField>
    <fullName>Resource_Availability__c</fullName>
    <label>Resource Availability</label>
    <referenceTo>PMT_Resource_Availability__c</referenceTo>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <label>Sep</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/PMT_Resource_Availability__c.object-meta.xml
<CustomObject>
    <description>Stores availability of a resource</description>
    <label>PMT Resource Availability</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Resource Availibility No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <description>Availability for April month</description>
    <label>Apr</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <description>Availability for August month</description>
    <label>Aug</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <description>Availability for February month</description>
    <label>Feb</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>The year for which availability is provided</description>
    <label>Fiscal Year</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <description>Availability for January month</description>
    <label>Jan</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <description>Availability for July month</description>
    <label>Jul</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <description>Availability for June month</description>
    <label>Jun</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <description>Availability for March month</description>
    <label>Mar</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <description>Availability for May month</description>
    <label>May</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Calculates the start date using FYXX format</description>
    <formula>If($CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c==1,
DATE(
VALUE(MID(TEXT(YEAR(TODAY())),1,2)
+
MID(Fiscal_Year__c, 3, 2)),
$CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c,1)
,
DATE(
VALUE(MID(TEXT(YEAR(TODAY())),1,2)
+
MID(Fiscal_Year__c, 3, 2))-1,
$CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c,1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for which availability is defined</description>
    <label>User</label>
    <referenceTo></referenceTo>
    <relationshipName>Resource_Availability</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Task__c/fields/Assigned_To1__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Employee</referenceTo>
    <relationshipName>PMT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Is_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone?</label>
    <type>Checkbox</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed, not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/PMT_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>On Track</fullName>
        <default>true</default>
        <label>On Track</label>
    </customValue>
    <customValue>
        <fullName>At Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Late</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed, not Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
        <isActive>false</isActive>
        <label>Complete</label>
    </customValue>
    <description>PMT Status list for Project</description>
    <masterLabel>PMT_Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMT_InstallHandler.cls
/******************************************************************************
* Name: PMT_InstallHandler.apxc
* Description : Creates a dummy project after installation on a sandbox or dev edition
* Test class : PMT_Testcoverage(100%)
******************************************************************************/
global with sharing class PMT_InstallHandler implements InstallHandler {
    global void onInstall(InstallContext context) {
        Id organizationId = context.organizationId();
        Id userId = context.installerID();
        if(context.previousVersion() == null) {
            try{
                Organization org = [Select id,InstanceName, OrganizationType, isSandbox from Organization where id=:organizationId with security_enforced limit 1];
                if(org?.isSandbox || org?.OrganizationType=='Developer Edition'){
                    PMT_Program__c program = new PMT_Program__c(
                        Name = 'Program 1',
                        OwnerId= userId,
                        Program_Health__c = 'On Track');
                    SObjectAccessDecision securityDecision = Security.stripInaccessible(
                        AccessType.CREATABLE, new List<PMT_Program__c>{program});
                    insert securityDecision.getRecords();
                    
                    PMT_Project__c project = new PMT_Project__c(
                        Name = 'Demo Project', 
                        Portfolio__c = 'R2R',
                        OwnerId= userId,
                        Initial_End_Date__c = System.today()+30,
                        Initial_Start_Date__c = System.today(),
                        Program__c = securityDecision.getRecords()[0]?.Id,
                        Level_of_Effort__c = 'Small');
                    securityDecision = Security.stripInaccessible(AccessType.CREATABLE, new List<PMT_Project__c>{project});
                    insert securityDecision.getRecords();
                    
                    Id projectId = securityDecision.getRecords()[0]?.Id;
                    List<PMT_Phase__c> lstOfPhases = new List<PMT_Phase__c>();
                    List<PMT_Task__c> lstOfTasks = new List<PMT_Task__c>();
                    Integer resourceAvailability = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Default_Availability_for_Scheduler__c);
                    //Create Phases
                    PMT_Phase__c phase1 = new PMT_Phase__c( Name = '0. Discovery',
                                                           Project__c = projectId);
                    
                    lstOfPhases.add(phase1);
                    
                    PMT_Phase__c phase2 = new PMT_Phase__c( Name = '1. Initiate',
                                                           Project__c = projectId);
                    
                    lstOfPhases.add(phase2);
                    
                    PMT_Phase__c phase3 = new PMT_Phase__c( Name = '2. Execute',
                                                           Project__c = projectId);
                    
                    lstOfPhases.add(phase3);
                    
                    PMT_Phase__c phase4 = new PMT_Phase__c( Name = '3. Transition',
                                                           Project__c = projectId);
                    
                    lstOfPhases.add(phase4);
                    
                    securityDecision = Security.stripInaccessible(AccessType.CREATABLE, lstOfPhases);
                    insert securityDecision.getRecords();
                    
                    //Create Tasks
                    PMT_Task__c task1 = new PMT_Task__c(
                        Name = '0.00 Project Start', 
                        Status__c = 'Completed',
                        Start_Date__c = System.today()-40, 
                        Due_Date__c = System.today()-10, 
                        Is_Milestone__c = true,
                        Assigned_to1__c = userId,
                        Phase__c = securityDecision.getRecords()[0]?.Id); 
                    lstOfTasks.add(task1);
                    
                    PMT_Task__c task2 = new PMT_Task__c(
                        Name ='1.1 Task 1', 
                        Status__c = 'In Progress',
                        Start_Date__c = System.today()-40, 
                        Due_Date__c = System.today()-10, 
                        Is_Milestone__c = false,
                        Phase__c = securityDecision.getRecords()[1]?.Id); 
                    lstOfTasks.add(task2);
                    
                    PMT_Task__c task3 = new PMT_Task__c(
                        Name = '2.1 Task 2', 
                        Status__c = 'Not Started',
                        Start_Date__c = System.today()-15, 
                        Due_Date__c = System.today(), 
                        Is_Milestone__c = false,
                        Assigned_to1__c = userId,
                        Phase__c = securityDecision.getRecords()[2]?.Id);
                    lstOfTasks.add(task3);
                    
                    PMT_Task__c task4 = new PMT_Task__c(
                        Name = '2.2 Task 3', 
                        Status__c = 'Not Started',
                        Start_Date__c = System.today()+40, 
                        Due_Date__c = System.today()+50, 
                        Is_Milestone__c = false, 
                        Phase__c = securityDecision.getRecords()[2]?.Id);
                    lstOfTasks.add(task4);
                    
                    PMT_Task__c task5 = new PMT_Task__c(
                        Name = '3.99 Project End', 
                        Status__c = 'Not Started',
                        Start_Date__c = System.today()+89, 
                        Due_Date__c = System.today()+90, 
                        Is_Milestone__c = false,
                        Assigned_to1__c = userId,
                        Phase__c = securityDecision.getRecords()[3]?.Id);
                    lstOfTasks.add(task5);
                    
                    securityDecision = Security.stripInaccessible(AccessType.CREATABLE, lstOfTasks);
                    insert securityDecision.getRecords();
                    
                    string fiscalYear = 'FY' + (Math.mod(system.today().year(), 1000)+1);
                    //Availability record
                    PMT_Resource_Availability__c resAvailwithUser = new PMT_Resource_Availability__c( User__c = userId,
                                                                                                     Fiscal_Year__c = fiscalYear,
                                                                                                     Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                                                     Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                                                     May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                                                     Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                                                     Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                                                     Nov__c = resourceAvailability, Dec__c = resourceAvailability);
                    
                    PMT_Resource_Availability__c resAvailWOUSer = new PMT_Resource_Availability__c(Fiscal_Year__c = fiscalYear,
                                                                                                   Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                                                   Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                                                   May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                                                   Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                                                   Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                                                   Nov__c = resourceAvailability, Dec__c = resourceAvailability);
                    securityDecision = Security.stripInaccessible(AccessType.CREATABLE, new List<PMT_Resource_Availability__c>{resAvailwithUser, resAvailWOUSer});
                    insert securityDecision.getRecords();
                    
                    List<PMT_Resource_Allocation__c> lstAllocation = new List<PMT_Resource_Allocation__c>();
                    
                    //Allocation records
                    PMT_Resource_Allocation__c resAllocation = new PMT_Resource_Allocation__c(Project__c = projectId,
                                                                                              Resource_Availability__c = securityDecision.getRecords()[1]?.Id,
                                                                                              Role__c = 'SME');
                    lstAllocation.add(resAllocation);
                    securityDecision = Security.stripInaccessible(AccessType.CREATABLE, lstAllocation);
                    insert securityDecision.getRecords();
                }
            }
            catch(Exception e){
                System.debug(e.getMessage());
            }
        }
    }
}