sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Phase__c/fields/Health_Icon__c.field-meta.xml
<CustomField>
    <fullName>Health_Icon__c</fullName>
    <formula>IMAGE(
CASE(Phase_Health__c,
&quot;Not Started&quot;, &quot;/resource/PMT_Status_logos/Not_Started.png&quot;,
&quot;On Track&quot;, &quot;/resource/PMT_Status_logos/On_Track.png&quot;,
&quot;At risk&quot;, &quot;/resource/PMT_Status_logos/At_Risk.png&quot;,
&quot;Late&quot;, &quot;/resource/PMT_Status_logos/Late.png&quot;,
&quot;On Hold&quot;, &quot;/resource/PMT_Status_logos/On_Hold.png&quot;,
&quot;Completed&quot;, &quot;/resource/PMT_Status_logos/Completed.png&quot;,
&quot;Closed, not Completed&quot;, &quot;/resource/PMT_Status_logos/Closed_not_Completed.png&quot;,
&quot;/resource/PMT_Status_logos/On_Track.png&quot;),
&quot;status icon&quot;,25,25)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase Health</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Phase__c/fields/Kickoff_formula__c.field-meta.xml
<CustomField>
    <fullName>Kickoff_formula__c</fullName>
    <formula>IF(ISNULL(Start_Date_Rollup__c),  IF(ISNULL( Start_date_from_child_project__c), Project__r.Kickoff_formula__c, Start_date_from_child_project__c) ,Start_Date_Rollup__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Phase_Completion__c.field-meta.xml
<CustomField>
    <fullName>Phase_Completion__c</fullName>
    <formula>FLOOR((Sum_Weighted_perc__c / Sum_Task_Duration__c)*100)/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase Completion %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Phase__c/fields/Phase_Completion_Image__c.field-meta.xml
<CustomField>
    <fullName>Phase_Completion_Image__c</fullName>
    <formula>IMAGE(&quot;/resource/PMT_Status_Images/PMT_Percent_100.jpg&quot;, &quot;Completed&quot;, 10, ( Phase_Completion__c * 100 )/1.3) &amp; 
IMAGE(&quot;/resource/PMT_Status_Images/PMT_Percent_0.jpg&quot;, &quot;Zero&quot;, 10, (100 - Phase_Completion__c * 100 )/1.3) &amp; 
&apos; &apos; &amp; 
TEXT(ROUND(Phase_Completion__c * 100,0))&amp;&quot;%&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phase Completion</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Days_Late__c.field-meta.xml
<CustomField>
    <fullName>Days_Late__c</fullName>
    <formula>IF( ISPICKVAL(Status__c,&apos;Completed&apos;) || ISPICKVAL(Status__c,&apos;Closed, not Completed&apos;),0, Today() - Due_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Late</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Is_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone?</label>
    <type>Checkbox</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Project_Id__c</fullName>
    <formula>CASESAFEID(Phase__r.Project__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Status_Icon__c.field-meta.xml
<CustomField>
    <fullName>Status_Icon__c</fullName>
    <formula>IF(AND(Days_Late__c &gt;0,TEXT(Status__c) &lt;&gt; &quot;On Hold&quot;),IMAGE(&quot;/resource/PMT_Status_Images/PMT_warning_60.png&quot;,&quot;Late&quot;,20,20), 
IF( TEXT(Sign_off_status__c) = &quot;Approved&quot;, IMAGE(&quot;/resource/PMT_Status_Images/PMT_approval.png&quot;,&quot;Approved&quot;,20,20), 
CASE( TEXT(Status__c) , 
&quot;Not Started&quot;, IMAGE(&quot;/resource/PMT_Status_Images/PMT_routing_offline_60.png&quot;,&quot;Incomplete&quot;,20,20), 
&quot;In Progress&quot;, IMAGE(&quot;/resource/PMT_Status_Images/PMT_Clock.png&quot;,&quot;In Progress&quot;,20,20), 
&quot;On Hold&quot;,IMAGE(&quot;/resource/PMT_Status_Images/PMT_error_60.png&quot;,&quot;On Hold&quot;,20,20), 
IMAGE(&quot;/resource/PMT_Status_Images/PMT_success_60.png&quot;,&quot;Closed&quot;,20,20))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Icon</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/classes/PMT_ProjectSummaryCtrl.cls
/******************************************************************************
* Name: PMT_ProjectSummaryCtrl.apxc
* Used by: Used by PMT_ProjectSummaryPhaseTable.cmp
* Description : It contains methods to find out phases, tasks, milestones related to PMT project
* Test class : PMT_Testcoverage(85%)
******************************************************************************/

public with sharing class PMT_ProjectSummaryCtrl {

    /*************************************************
    * Name: createSummaryWrapper
    * Description: Create wrapper for lists
    * ***********************************************/
  
    public class CreateSummaryWrapper
    {
        @AuraEnabled public List<PMT_Phase__c> phasesList;
        @AuraEnabled public List<PMT_Task__c> lateTaskList;
        @AuraEnabled public List<PMT_Task__c> onGoingTaskList;
        @AuraEnabled public List<PMT_Task__c> milestoneTaskList;
        @AuraEnabled public integer fiscalMonthOffset;
    }
    
    /************************************************
    * Method Name: getSummaryWrapper 
    * Description: Wrapper for getPhasesForProject and getTasksForProject methods
    * Parameters : recordId
    * Return Values: list of Tasks and list of phases
    * ***********************************************/    
    @AuraEnabled
    public static CreateSummaryWrapper getSummaryWrapper(Id recordId)
    {
		CreateSummaryWrapper summaryWrapper = new CreateSummaryWrapper();
        //Calling util method to check CRUD
		List<String> lstOfPhaseFields = new List<String>{'Name', 'Health_Icon__c', 'Phase_Completion__c', 'Phase_Completion_Image__c', 'Project__c','Kickoff_formula__c'};
		if (PMT_Utility.validateCRUD('PMT_Phase__c', lstOfPhaseFields, 'isAccessible') ){ 
			summaryWrapper.phasesList = getPhasesForProject(recordId);
		}else{
			throw new AuraHandledException('You don\'t have access to PMT Phases. Please contact system administrator.');
		}
		
        //Calling util method to check CRUD
		List<String> lstOfTaskFields = new List<String>{'Name', 'Status_Icon__c', 'Start_Date__c', 'Due_Date__c', 'Is_Milestone__c', 'Phase__c', 'Days_Late__c', 'Project_Id__c'};
		if (PMT_Utility.validateCRUD('PMT_Task__c', lstOfTaskFields, 'isAccessible') ){ 
			summaryWrapper.lateTaskList = getLateTasksForProject(recordId);
			
			summaryWrapper.onGoingTaskList = getOnGoingTasksForProject(recordId);
			
			summaryWrapper.milestoneTaskList = getMilestoneTasksForProject(recordId);
		}else{
			throw new AuraHandledException('You don\'t have access to PMT Task. Please contact system administrator.');
		}		
		
        //Get PMT Settings
        summaryWrapper.fiscalMonthOffset = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Start_Month_of_Fiscal_Year__c);
		return summaryWrapper;      
    }
    
    /*************************************************
    * Method Name: getPhasesForProject
    * Description: Get list of Phases for a project
    * Parameters : recordId
    * Return Values: list of phases
    * ***********************************************/  
    private static List<PMT_Phase__c> getPhasesForProject(Id recordId)
    {
		return [SELECT id,Name,Health_Icon__c,Phase_Completion__c, Phase_Completion_Image__c,Kickoff_formula__c FROM PMT_Phase__c 
                WHERE Project__c=:recordId ORDER BY Kickoff_formula__c ASC limit: limits.getLimitQueryRows()];                    
	}

    /*************************************************
    * Method Name: getLateTasksForProject
    * Description: Get list of Tasks for a project
    * Parameters : recordId
    * Return Values: list of late tasks
    * ***********************************************/  
    private static List<PMT_Task__c> getLateTasksForProject(Id recordId)
    {
		return [SELECT id,Name,Status_Icon__c,Start_Date__c,Due_Date__c,Is_Milestone__c,Phase__c,Days_Late__c FROM PMT_Task__c 
				WHERE Project_Id__c=:recordId AND Days_Late__C > 0 order by Due_Date__c ASC, Name ASC limit: limits.getLimitQueryRows()];
    }

    /*************************************************
    * Method Name: getOnGoingTasksForProject
    * Description: Get list of OnGoing Tasks set for a project
    * Parameters : recordId
    * Return Values: list of ongoing tasks (not Late)
    * ***********************************************/  
    private static List<PMT_Task__c> getOnGoingTasksForProject(Id recordId)
    {
		return [SELECT id,Name,Status_Icon__c,Start_Date__c,Due_Date__c,Is_Milestone__c,Phase__c,Phase__r.Name,    Days_Late__c FROM PMT_Task__c 
				WHERE Project_Id__c=:recordId AND Days_Late__C <= 0 order by Due_Date__c ASC, Name ASC limit: limits.getLimitQueryRows()];					      
    }

    /*************************************************
    * Method Name: getMilestoneTasksForProject
    * Description: Get list of Milestone Tasks set for a project
    * Parameters : recordId
    * Return Values: list of Milestone tasks
    * ***********************************************/  
    private static List<PMT_Task__c> getMilestoneTasksForProject(Id recordId)
    {
		return [SELECT id,Name,Status_Icon__c,Due_Date__c FROM PMT_Task__c 
				WHERE Project_Id__c=:recordId AND Is_Milestone__c=true order by Due_Date__c ASC, Name ASC limit: limits.getLimitQueryRows()];					
		 
    }
    
}