sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Phase__c/fields/Phase_Health__c.field-meta.xml
<CustomField>
    <fullName>Phase_Health__c</fullName>
    <label>Phase Health</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>On Track</fullName>
                <default>true</default>
                <label>On Track</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Late</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed, not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Project__c/PMT_Project__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A project can one or more phases</description>
    <label>PMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Project__c/fields/Initial_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_End_Date__c</fullName>
    <label>Initial End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTemplate?</label>
    <type>Checkbox</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Level_of_Effort__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Effort__c</fullName>
    <label>Level of Effort</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F&amp;S</fullName>
            </value>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>Q2O</fullName>
            </value>
            <value>
                <fullName>R2R</fullName>
            </value>
            <value>
                <fullName>New Entity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <inlineHelpText>The date this task is due to be completed</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Duration_In_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Days__c</fullName>
    <label>Duration In Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Is_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Is_Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Milestone?</label>
    <type>Checkbox</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>IsTemplate__c</fullName>
    <formula>Phase__r.Project__r.IsTemplate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsTemplate?</label>
    <type>Checkbox</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Start_Days_Out__c.field-meta.xml
<CustomField>
    <fullName>Start_Days_Out__c</fullName>
    <label>Start Days Out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed, not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMT_ClonePhaseTaskCtrlTest.cls
/********************************************************
* Name: PMT_ClonePhaseTaskCtrlTest
* Test class for : PMT_ClonePhaseTaskCtrl (85%)
* Version : 56
* *******************************************************/

@isTest
public class PMT_ClonePhaseTaskCtrlTest {
    
    @testSetup static void setup() {
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
        
        User usr = new User(Alias = 'standt', Email = 'standarduser@pmttemplate.com',
                            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                            LocaleSidKey = 'en_US', ProfileId = p.Id,
                            TimeZoneSidKey = 'America/Los_Angeles', UserName = 'standarduser@pmtdeepclone.com');
        
        insert usr;
        
        List<PermissionSetAssignment> lstOfPSA = new List<PermissionSetAssignment> ();
        
        for (PermissionSet psRec: [SELECT Id FROM PermissionSet WHERE Name IN('PMT_User')]) {
            PermissionSetAssignment psa = new PermissionSetAssignment(AssigneeId = usr.Id, PermissionSetId = psRec.Id);
            lstOfPSA.add(psa);
        }
        
        INSERT lstOfPSA;
        
        System.runAs(usr) {
            
            List<PMT_Task__c > lstOfTasks = new List<PMT_Task__c > ();
            
            //PMT project record
            PMT_Project__c project = new PMT_Project__c(Name = 'Clone Phases/Tasks Test',
                                                        Portfolio__c = 'R2R',
                                                        Initial_End_Date__c = System.today() + 30,
                                                        Initial_Start_Date__c = System.today(),
                                                        Level_of_Effort__c = 'Medium'
                                                        //TShirtSize__c = 'Explorer'
                                                       );
            INSERT project;
            
            //PMT project template record
            PMT_Project__c templateProject = new PMT_Project__c(Name = 'Template Project',
                                                                Portfolio__c = 'R2R',
                                                                Initial_End_Date__c = System.today() + 30,
                                                                Initial_Start_Date__c = System.today(),
                                                                Level_of_Effort__c = 'Medium',
                                                                IsTemplate__c = true
                                                                //TShirtSize__c = 'Explorer'
                                                               );
            INSERT templateProject;
            
            //PMT phase record
            PMT_Phase__c phases = new PMT_Phase__c(Name = 'Phase 1',
                                                   Project__c = project.Id, Phase_Health__c = 'On Track');
            INSERT phases;
            
            //PMT phase record
            PMT_Phase__c phases1 = new PMT_Phase__c(Name = 'Phase Template',
                                                    Project__c = templateProject.Id, Phase_Health__c = 'On Track');
            INSERT phases1;
            
            //PMT Task records
            PMT_Task__c task3 = new PMT_Task__c(Name = 'Task Template',
                                                Status__c = 'Not Started',
                                                Start_Date__c = System.today(),
                                                Due_Date__c = System.today() + 30,
                                                Is_Milestone__c = true,
                                                Start_Days_Out__c = 2,
                                                Duration_In_Days__c = 5,
                                                Phase__c = phases1.Id);
            lstOfTasks.add(task3);
            
            //PMT Task records
            PMT_Task__c task1 = new PMT_Task__c(Name = 'Task 1',
                                                Status__c = 'Not Started',
                                                Start_Date__c = System.today(),
                                                Due_Date__c = System.today() + 30,
                                                Is_Milestone__c = true,
                                                Phase__c = phases.Id);
            lstOfTasks.add(task1);
            
            PMT_Task__c task2 = new PMT_Task__c(Name = 'Task 2',
                                                Status__c = 'Not Started',
                                                Start_Date__c = System.today(),
                                                Due_Date__c = System.today() + 30,
                                                Is_Milestone__c = false,
                                                Phase__c = phases.Id);
            lstOfTasks.add(task2);
            
            INSERT lstOfTasks;
        }
    }
    
/*****************************************************************
* Method Name: getTasksforSelectedPhases 
* Class : PMT_ClonePhaseTaskCtrl 
******************************************************************/
    static testmethod void getTasksforSelectedPhases() {
        
        User testUser = [select id from User where Email = 'standarduser@pmttemplate.com'];
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            List<PMT_Task__c> lstTasks;
            List<PMT_Project__c> lstProj = [select id from PMT_Project__c where Name = 'Clone Phases/Tasks Test'];
            
            PMT_ClonePhaseTaskCtrl.FlowInputs wrap = new PMT_ClonePhaseTaskCtrl.FlowInputs();
            wrap.phases = [select id from PMT_Phase__c where Project__c=:lstProj[0].Id];
            wrap.projectId = lstProj[0].Id;
            wrap.phaseCheck = true;
            
            List<PMT_ClonePhaseTaskCtrl.FlowInputs > paramList = new List<PMT_ClonePhaseTaskCtrl.FlowInputs > ();
            paramList.add(wrap);
            
            List<PMT_ClonePhaseTaskCtrl.FlowOutputs > outputList = PMT_ClonePhaseTaskCtrl.getTasks(paramList);
            
            for(PMT_ClonePhaseTaskCtrl.FlowOutputs tasks: outputList){
                lstTasks = tasks.outputTasks;
            }
            System.assertEquals(2, lstTasks.size(), 'There should be 2 tasks returned.');
            Test.stopTest();
        }
    }
    
/*****************************************************************
* Method Name: cloneProjectFromTemplates
* Class : PMT_ClonePhaseTaskCtrl 
******************************************************************/
    static testmethod void cloneProjectFromTemplates() {
        User testUser = [select id from User where Email = 'standarduser@pmttemplate.com'];
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            List<PMT_Project__c> lstProj = [select id from PMT_Project__c where IsTemplate__c=true];
            
            PMT_ClonePhaseTaskCtrl.FlowInputs wrap = new PMT_ClonePhaseTaskCtrl.FlowInputs();
            wrap.phases = [select id, Name, Project__c, Phase_Health__c from PMT_Phase__c where Project__c=:lstProj[0].Id];
            wrap.tasks = [select id from PMT_Task__c where Name='Task Template'];
            wrap.projectId = lstProj[0].Id;
            wrap.phaseCheck = false;
            wrap.projectName = 'Test Template Project';
            wrap.projectStartDate = System.Today();
            
            List<PMT_ClonePhaseTaskCtrl.FlowInputs > paramList = new List<PMT_ClonePhaseTaskCtrl.FlowInputs > ();
            paramList.add(wrap);
            
            PMT_ClonePhaseTaskCtrl.getTasks(paramList);
            
            List<PMT_Project__c> lstProj1 = [select id from PMT_Project__c where Name='Test Template Project'];
            
            system.assertEquals(1, lstProj1.size(), 'There should be 1 new Project created from Template');
            
            Test.stopTest();
        }
    }
    
/*****************************************************************
* Method Name: cloneSelectedPhases
* Class : PMT_ClonePhaseTaskCtrl 
******************************************************************/
    static testmethod void cloneSelectedPhases() {
        User testUser = [select id from User where Email = 'standarduser@pmttemplate.com'];
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            List<PMT_Project__c> lstProj = [select id from PMT_Project__c where Name='Clone Phases/Tasks Test'];
            
            PMT_ClonePhaseTaskCtrl.FlowInputs wrap = new PMT_ClonePhaseTaskCtrl.FlowInputs();
            wrap.phases = [select id, Name, Project__c, Phase_Health__c from PMT_Phase__c where Name='Phase 1'];
            wrap.projectId = lstProj[0].Id;
            wrap.phaseCheck = false;
            
            List<PMT_ClonePhaseTaskCtrl.FlowInputs > paramList = new List<PMT_ClonePhaseTaskCtrl.FlowInputs > ();
            paramList.add(wrap);
            
            PMT_ClonePhaseTaskCtrl.getTasks(paramList);
            
            Test.stopTest();
            List<PMT_Phase__c> lstPhases = [select id, Phase_Health__c from PMT_Phase__c where Name='Phase 1'];
            
            system.assertEquals(2, lstPhases.size(), 'There should be 2 phases returned.');
        }
    }
    
/*****************************************************************
* Method Name: cloneSelectedTasks
* Class : PMT_ClonePhaseTaskCtrl 
******************************************************************/
    static testmethod void cloneSelectedTasks() {
        User testUser = [select id from User where Email = 'standarduser@pmttemplate.com'];
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            List<PMT_Project__c> lstProj = [select id from PMT_Project__c];
            
            PMT_ClonePhaseTaskCtrl.FlowInputs wrap = new PMT_ClonePhaseTaskCtrl.FlowInputs();
            wrap.phases = [select id from PMT_Phase__c where Name='Phase 1'];
            wrap.tasks = [select id, Phase__c from PMT_Task__c where Name='Task 1'];
            wrap.projectId = lstProj[0].Id;
            wrap.phaseCheck = false;
            
            List<PMT_ClonePhaseTaskCtrl.FlowInputs > paramList = new List<PMT_ClonePhaseTaskCtrl.FlowInputs > ();
            paramList.add(wrap);
            
            PMT_ClonePhaseTaskCtrl.getTasks(paramList);
            
            Test.stopTest();
            
            List<PMT_Task__c> lstTasks = [select id from PMT_Task__c where Name='Task 1'];
            system.assertEquals(2, lstTasks.size(), 'There should be 2 tasks returned.');
        }
    }
    
/*****************************************************************
* Method Name: cloneSelectedPhasesNegative
* Class : PMT_ClonePhaseTaskCtrl 
******************************************************************/
    static testmethod void cloneSelectedPhasesNegative() {
        User testUser = [select id from User where Email = 'standarduser@pmttemplate.com'];
        
        System.runAs(testUser) {
            
            Test.startTest();
            
            PMT_ClonePhaseTaskCtrl.FlowInputs wrap = new PMT_ClonePhaseTaskCtrl.FlowInputs();
            wrap.phases = [select id from PMT_Phase__c];
            wrap.phaseCheck = false;
            
            List<PMT_ClonePhaseTaskCtrl.FlowInputs > paramList = new List<PMT_ClonePhaseTaskCtrl.FlowInputs > ();
            paramList.add(wrap);
            
            PMT_ClonePhaseTaskCtrl.getTasks(paramList);
            
            wrap.phases = new List<PMT_Phase__c > ();
            wrap.tasks = [select id, Phase__c from PMT_Task__c];
            wrap.projectStartDate = System.Today();
            
            PMT_ClonePhaseTaskCtrl.getTasks(paramList);
            
            Test.stopTest();
            
            List<PMT_Phase__c> lstPhases = [select id from PMT_Phase__c where Name='Phase 1'];
            System.assertEquals(1, lstPhases.size(), 'There should be only 1 Phase returned due to failure');
        }
    }
}