sfdc-pmt/main/default/objects/PMT_Phase__c/PMT_Phase__c.object-meta.xml
<CustomObject>
    <description>Phases are significant events in the life-cycle of a Project. Phases can have tasks associated with them.</description>
    <label>PMT Phase</label>
    <nameField>
        <label>Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Phase__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>The project this phase is assigned to</description>
    <label>Project Name</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipLabel>PMT Phases</relationshipLabel>
    <relationshipName>Project_Phases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/PMT_Project__c.object-meta.xml
<CustomObject>
    <description>A collaborative enterprise which has a planned goal. A project can one or more phases</description>
    <label>PMT Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Initial_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Initial End Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Project__c/fields/Level_of_Effort__c.field-meta.xml
<CustomField>
    <fullName>Level_of_Effort__c</fullName>
    <label>Level of Effort</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Project__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <label>Portfolio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F&amp;S</fullName>
            </value>
            <value>
                <fullName>P2P</fullName>
            </value>
            <value>
                <fullName>Q2O</fullName>
            </value>
            <value>
                <fullName>R2R</fullName>
            </value>
            <value>
                <fullName>New Entity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/PMT_Resource_Allocation__c.object-meta.xml
<CustomObject>
    <description>Stores the allocation of the resource for a requirement</description>
    <label>PMT Resource Allocation</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Resource Allocation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <label>Apr</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <label>Aug</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <label>Dec</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <label>Feb</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <formula>Resource_Availability__r.Fiscal_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Year</label>
    <type>Text</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Allocation__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <label>Jan</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <label>Jul</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <label>Jun</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <label>Mar</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <label>May</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <label>Nov</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <label>Oct</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>PMT_Project__c</referenceTo>
    <relationshipName>Resource_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Resource_Availability__c.field-meta.xml
<CustomField>
    <fullName>Resource_Availability__c</fullName>
    <label>Resource Availability</label>
    <referenceTo>PMT_Resource_Availability__c</referenceTo>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PMT_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMT_Resource_Allocation__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <label>Sep</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/PMT_Resource_Availability__c.object-meta.xml
<CustomObject>
    <description>Stores availability of a resource</description>
    <label>PMT Resource Availability</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Resource Availibility No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Apr__c.field-meta.xml
<CustomField>
    <fullName>Apr__c</fullName>
    <description>Availability for April month</description>
    <label>Apr</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Aug__c.field-meta.xml
<CustomField>
    <fullName>Aug__c</fullName>
    <description>Availability for August month</description>
    <label>Aug</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Dec__c.field-meta.xml
<CustomField>
    <fullName>Dec__c</fullName>
    <description>Availability for December month</description>
    <label>Dec</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Feb__c.field-meta.xml
<CustomField>
    <fullName>Feb__c</fullName>
    <description>Availability for February month</description>
    <label>Feb</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>The year for which availability is provided</description>
    <label>Fiscal Year</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Jan__c.field-meta.xml
<CustomField>
    <fullName>Jan__c</fullName>
    <description>Availability for January month</description>
    <label>Jan</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jul__c.field-meta.xml
<CustomField>
    <fullName>Jul__c</fullName>
    <description>Availability for July month</description>
    <label>Jul</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Jun__c.field-meta.xml
<CustomField>
    <fullName>Jun__c</fullName>
    <description>Availability for June month</description>
    <label>Jun</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/Mar__c.field-meta.xml
<CustomField>
    <fullName>Mar__c</fullName>
    <description>Availability for March month</description>
    <label>Mar</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Resource_Availability__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <description>Availability for May month</description>
    <label>May</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Nov__c.field-meta.xml
<CustomField>
    <fullName>Nov__c</fullName>
    <description>Availability for November month</description>
    <label>Nov</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Oct__c.field-meta.xml
<CustomField>
    <fullName>Oct__c</fullName>
    <description>Availability for October month</description>
    <label>Oct</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Sep__c.field-meta.xml
<CustomField>
    <fullName>Sep__c</fullName>
    <description>Availability for September month</description>
    <label>Sep</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Calculates the start date using FYXX format</description>
    <formula>If($CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c==1,
DATE(
VALUE(MID(TEXT(YEAR(TODAY())),1,2)
+
MID(Fiscal_Year__c, 3, 2)),
$CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c,1)
,
DATE(
VALUE(MID(TEXT(YEAR(TODAY())),1,2)
+
MID(Fiscal_Year__c, 3, 2))-1,
$CustomMetadata.PMT_Setting__mdt.Default.Start_Month_of_Fiscal_Year__c,1)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for which availability is defined</description>
    <label>User</label>
    <referenceTo></referenceTo>
    <relationshipName>Resource_Availability</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/PMT_Task__c.object-meta.xml
<CustomObject>
    <description>An activity that has been assigned to a User.</description>
    <label>PMT Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PMT Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Assigned_To1__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMT_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-pmt/main/default/objects/PMT_Task__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <inlineHelpText>The phase that this task is assigned to.</inlineHelpText>
    <label>Phase</label>
    <referenceTo>PMT_Phase__c</referenceTo>
    <relationshipLabel>PMT Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PMT_Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>When should this task start by?</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

sfdc-pmt/main/default/classes/PMT_ResourceAllocationTriggerTest.cls
/****************************************************************************************
* Name: PMT_ResourceAllocationTriggerTest
* Test Class For: PMT_ResourceAllocationTrigger (84%)
				  PMT_ResourceAllocationTriggerHelper (90%)	
****************************************************************************************/
@isTest 
public class PMT_ResourceAllocationTriggerTest {
    @testSetup static void setup(){
        System.runAs(new User(Id = Userinfo.getUserId())) {
            Integer resourceAvailability = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Default_Availability_for_Scheduler__c);
            
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' limit 1]; 
            User usr = new User(Alias = 'pmtuser1', Email='pmtuser@testorg.com', 
                                EmailEncodingKey='UTF-8', LastName='userTesting', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id,Department='IT', 
                                TimeZoneSidKey='America/Los_Angeles', UserName='pmtuser@testorg.com'); 
            
            INSERT usr ;
            
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PMT_Global_Admin'];
            INSERT new PermissionSetAssignment(AssigneeId = usr.id, PermissionSetId = ps.Id);            
            
            //Project record
            PMT_Project__c project = new PMT_Project__c(Name='Single Project Controller Test', 
                                                        Portfolio__c='R2R',
                                                        Initial_End_Date__c=System.today()+30,
                                                        Initial_Start_Date__c=System.today(),
                                                       Level_of_Effort__c = 'Small');
            INSERT project;
            
            //Availability record
            PMT_Resource_Availability__c resAvail = new PMT_Resource_Availability__c( User__c = UserInfo.getUserId(),
                                                                                     Fiscal_Year__c = 'FY20',
                                                                                     Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                                     Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                                     May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                                     Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                                     Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                                     Nov__c = resourceAvailability, Dec__c = resourceAvailability);
            INSERT resAvail;
        }
    }
    
    static testmethod void projectSharingTestCase(){        
 		System.runAs(new User(Id = Userinfo.getUserId())) {  
            User usr = [SELECT Id FROM User WHERE Email='pmtuser@testorg.com'];
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            PMT_Resource_Availability__c resAvail = [SELECT Id FROM PMT_Resource_Availability__c LIMIT 1];
            System.runAs(usr) {
                Test.startTest();
                //Allocation records
                PMT_Resource_Allocation__c resAllocation = new PMT_Resource_Allocation__c(Project__c = project.Id,
                                                                                          Resource_Availability__c = resAvail.Id,
                                                                                          Role__c = 'SME' );                                                                                        
                INSERT resAllocation;
                
                List<PMT_Project__Share> ls = [select Id from PMT_Project__Share where ParentId =: project.Id and UserOrGroupId =: UserInfo.getUserId()];
                
                System.assertNotEquals(null, ls, 'Project sharing done');
                Test.stopTest();
            }
        }
    }
    
    static testmethod void allocationWOTaskDeletionTestCase(){        
 		System.runAs(new User(Id = Userinfo.getUserId())) {  
            User usr = [SELECT Id FROM User WHERE Email='pmtuser@testorg.com'];
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            PMT_Resource_Availability__c resAvail = [SELECT Id FROM PMT_Resource_Availability__c LIMIT 1];
            //Allocation records
             PMT_Resource_Allocation__c resAllocation = new PMT_Resource_Allocation__c(Project__c = project.Id,
                                                                                          Resource_Availability__c = resAvail.Id,
                                                                                          Role__c = 'SME' ); 
            INSERT resAllocation;
            
            System.runAs(usr) {
                Test.startTest();
                    DELETE resAllocation;
                    List<PMT_Project__Share> ls = [select Id from PMT_Project__Share where ParentId =: project.Id and UserOrGroupId =: UserInfo.getUserId()];                
                	System.assertNotEquals(null, ls, 'Record founding for deletion');
                Test.stopTest();
            }
        }
    }
    
     static testmethod void allocationWithTaskDeletionTestCase(){        
 		System.runAs(new User(Id = Userinfo.getUserId())) {  
            User usr = [SELECT Id FROM User WHERE Email='pmtuser@testorg.com'];
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            
            PMT_Phase__c phase = new PMT_Phase__c(Name='Develop', Project__c = project.Id);
            INSERT phase;
            
            PMT_Task__c task = new PMT_Task__c(Phase__c = phase.Id, Assigned_To1__c = UserInfo.getUserId(), Start_Date__c = System.today(), Due_Date__c= System.today()+10);
			INSERT task;
            
            PMT_Resource_Availability__c resAvail = [SELECT Id FROM PMT_Resource_Availability__c LIMIT 1];
            //Allocation records
             PMT_Resource_Allocation__c resAllocation = new PMT_Resource_Allocation__c(Project__c = project.Id,
                                                                                          Resource_Availability__c = resAvail.Id,
                                                                                          Role__c = 'SME' ); 
            INSERT resAllocation;
            
            System.runAs(usr) {
                Test.startTest();
                try{
                	DELETE resAllocation;
                    List<PMT_Project__Share> ls = [select Id from PMT_Project__Share where ParentId =: project.Id and UserOrGroupId =: UserInfo.getUserId()];                
                }catch(Exception e){
                  System.assertNotEquals(null, e.getMessage(),'error should be returned for negative test');  
                }
                    
                Test.stopTest();
            }
        }
    }
    
    static testmethod void projectUpdateTestCase(){        
 		System.runAs(new User(Id = Userinfo.getUserId())) {  
            Integer resourceAvailability = Integer.valueOf(PMT_Utility.getPMTSettings('Default').Default_Availability_for_Scheduler__c);
            
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' limit 1]; 
            User pmtTempUser = new User(Alias = 'usrpmt', Email='pmtTempUser@testorg.com', 
                                EmailEncodingKey='UTF-8', LastName='pmtTempUser', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id,Department='Sales', 
                                TimeZoneSidKey='America/Los_Angeles', UserName='pmtTempUser@testorg.com'); 
            
            INSERT pmtTempUser;
            
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PMT_Global_Admin'];
            INSERT new PermissionSetAssignment(AssigneeId = pmtTempUser.id, PermissionSetId = ps.Id);
            
            PMT_Resource_Availability__c resAvailNew = new PMT_Resource_Availability__c(User__c = pmtTempUser.Id,
                                                                              Fiscal_Year__c = 'FY21',
                                                                              Jan__c = resourceAvailability, Feb__c = resourceAvailability, 
                                                                              Mar__c = resourceAvailability, Apr__c = resourceAvailability, 
                                                                              May__c = resourceAvailability, Jun__c = resourceAvailability, 
                                                                              Jul__c = resourceAvailability, Aug__c = resourceAvailability, 
                                                                              Sep__c = resourceAvailability, Oct__c = resourceAvailability,
                                                                              Nov__c = resourceAvailability, Dec__c = resourceAvailability);
                                                                            
            INSERT resAvailNew;
            
            PMT_Project__c project = [SELECT Id FROM PMT_Project__c LIMIT 1];
            PMT_Resource_Availability__c resAvail = [SELECT Id FROM PMT_Resource_Availability__c LIMIT 1];
            //Allocation records
             PMT_Resource_Allocation__c resAllocation = new PMT_Resource_Allocation__c(Project__c = project.Id,
                                                                                          Resource_Availability__c = resAvail.Id,
                                                                                          Role__c = 'SME' ); 
            
            INSERT resAllocation;
            
            User usr = [SELECT Id FROM User WHERE Email='pmtuser@testorg.com'];
            System.runAs(usr) {                
                Test.startTest();
                	resAllocation.Resource_Availability__c = resAvailNew.Id;
                	UPDATE resAllocation;
                
                List<PMT_Project__Share> lsNew = [select Id from PMT_Project__Share where ParentId =: project.Id and UserOrGroupId =: pmtTempUser.Id];
                List<PMT_Project__Share> lsOld = [select Id from PMT_Project__Share where ParentId =: project.Id and UserOrGroupId =: usr.Id];
                
                System.assertNotEquals(null, lsNew, 'Project sharing done for new resource');
                System.assertNotEquals(null, lsOld, 'Project sharing revoked for old resource');
                
                Test.stopTest();
            }
        }
    }
    
}