force-app/main/default/objects/PMT_Resource_Availability__c/PMT_Resource_Availability__c.object-meta.xml
<CustomObject>
    <description>Stores availability of a resource</description>
    <label>PMT Resource Availability</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Resource Availibility No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PMT Resource Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMT_Resource_Availability__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User for which availability is defined</description>
    <label>User</label>
    <referenceTo></referenceTo>
    <relationshipName>Resource_Availability</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdc-pmt/main/default/objects/User/fields/Is_PMT_User_consider_for_Availability__c.field-meta.xml
<CustomField>
    <fullName>Is_PMT_User_consider_for_Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies user as PMT user consider for Resource Availability</description>
    <label>Is PMT User consider for Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PMT_ResourceAvailabilitySchedulerTest.cls
/***********************************************************************************************************
 * Name: PMT_ResourceAvailabilitySchedulerTest
 * Test Class for: PMT_CreateResourceAvailability (86%)
 *                 PMT_ResourceAvailabilityScheduler (100%)
 ***********************************************************************************************************/
@isTest 
Public class PMT_ResourceAvailabilitySchedulerTest{
    /*****************************************************************
     * Method Name : updateUserTestCase
     * Description : Test method for unit testing process automation written on User
     * **************************************************************/
    static testMethod void updateUserTestCase(){       
            User testUser = PMT_Testcoverage.createUser('System Administrator', new List<String>{'PMT_Resource_Planner'});
            System.runAs(testUser){
                Profile standardprofile = [SELECT Id FROM Profile WHERE Name='Standard User'];
                
                User pmtUsr = new User(Alias = 'PMT', Email='PMTUser@testClass.com', 
                EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = standardprofile.Id, 
                TimeZoneSidKey='America/Los_Angeles', UserName='PMTUser@testClass.com', IsActive = true);
                INSERT pmtUsr;
            
            
                Test.startTest();
                PMT_CreateResourceAvailability.createRAOnUserInsert(new List<Id>{pmtUsr.Id});
                Test.stopTest();
                List<PMT_Resource_Availability__c> lstOfResourceAvailability = [SELECT id FROM PMT_Resource_Availability__c WHERE User__c =: pmtUsr.Id];
                System.assertEquals(lstOfResourceAvailability.size()>0 , true, 'Resource availability should be created for user.');
           }     
          
    }
    
    /*****************************************************************
     * Method Name : updateUserTestCase
     * Description : Test method for unit testing scheduler which creates Resource availability for all PMT users
     * **************************************************************/
    static testMethod void apexSchedulerTestCase(){
   
            Profile standardprofile = [SELECT Id FROM Profile WHERE Name='Standard User'];
            
            User pmtUsr = new User(Alias = 'PMT', Email='PMTUser@testClass.com', 
            EmailEncodingKey='UTF-8', LastName='User', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = standardprofile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='PMTUser@testClass.com', IsActive = true, Department='Sales', Is_PMT_User_consider_for_Availability__c = true);
            INSERT pmtUsr;
            
            User testUser = PMT_Testcoverage.createUser('Standard User', new List<String>{'PMT_Resource_Planner'});
            System.runAs(testUser){
                Test.startTest();             
                    PMT_ResourceAvailabilityScheduler scheduler = new PMT_ResourceAvailabilityScheduler();
                    scheduler.execute(null);            
                Test.stopTest();
                List<PMT_Resource_Availability__c> lstOfResourceAvailability = [SELECT id FROM PMT_Resource_Availability__c WHERE User__c =: pmtUsr.Id];
                System.assertEquals(lstOfResourceAvailability.size()>0 , true, 'Resource availability should be created for user.');
            }
           
    }
}